#Real Estate Data Analytics Project
#Project ini bertujuan untuk menganalisis:
#- tren harga properti
#- tipe properti
#- distribusi harga
#- hubungan antara assessed value dan sale amount

#Dataset yang digunakan:
#Real Estate Sales Datase periode 2001-2022

# 🏠 Real Estate Data Analytics Project

# Project ini bertujuan untuk menganalisis:

# - tren harga properti
# - tipe properti
# - distribusi harga
# - hubungan antara assessed value dan sale amount

## Dataset yang digunakan

# Real Estate Sales Dataset periode 2001-2022.

In [2]:
print("Hi Data Analytics")

Hi Data Analytics

# import library untuk :
## membaca dataset
## mengolah data dan lanjut ke visualisasi dan analisa nya

In [7]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset real estate dengam menggunakan pandas data frame

In [8]:
df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")

C:\Users\SWIDJAJA\AppData\Local\Temp\ipykernel_11688\708756159.py:1: DtypeWarning: Columns (0: Property Type, 1: Residential Type, 2: Non Use Code, 3: Assessor Remarks, 4: OPM remarks) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Real_Estate_Sales_2001-2022_GL.csv")

## EDA yaitu Exploratory Data Analysis untuk pahami struktur dari 5 data pertama dari dataset nya.

In [10]:
df.head ()

,Unnamed: 0,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,NaN,NaN,POINT (-73.06822 41.35014)
1,1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,NaN,NaN
2,2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN,NaN,NaN
3,3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,NaN,NaN
4,4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,NaN,NaN,POINT (-72.879115982 41.773452988)

## Data set shape untuk melihat total baris dan kolom

In [12]:
df.shape

(1097629, 15)

## Dataset imformation = melihat non null atas tiap data dan jumlah data pada setiap kolom

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 15 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1097629 non-null  int64
 1   Serial Number     1097629 non-null  int64
 2   List Year         1097629 non-null  int64
 3   Date Recorded     1097627 non-null  str
 4   Town              1097629 non-null  str
 5   Address           1097578 non-null  str
 6   Assessed Value    1097629 non-null  float64
 7   Sale Amount       1097629 non-null  float64
 8   Sales Ratio       1097629 non-null  float64
 9   Property Type     715183 non-null   str
 10  Residential Type  699240 non-null   str
 11  Non Use Code      313451 non-null   object
 12  Assessor Remarks  171228 non-null   str
 13  OPM remarks       13031 non-null    str
 14  Location          298111 non-null   str
dtypes: float64(3), int64(3), object(1), str(8)
memory usage: 125.6+ MB

## Melihat type data angka bulat dan desimal juga text untuk alamat nya.

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 15 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1097629 non-null  int64
 1   Serial Number     1097629 non-null  int64
 2   List Year         1097629 non-null  int64
 3   Date Recorded     1097627 non-null  str
 4   Town              1097629 non-null  str
 5   Address           1097578 non-null  str
 6   Assessed Value    1097629 non-null  float64
 7   Sale Amount       1097629 non-null  float64
 8   Sales Ratio       1097629 non-null  float64
 9   Property Type     715183 non-null   str
 10  Residential Type  699240 non-null   str
 11  Non Use Code      313451 non-null   object
 12  Assessor Remarks  171228 non-null   str
 13  OPM remarks       13031 non-null    str
 14  Location          298111 non-null   str
dtypes: float64(3), int64(3), object(1), str(8)
memory usage: 125.6+ MB

## Cleaning : cek missing, hapus kolom yang tidak penting, lihat ada kah duplikasi dan lanjut ke filtering data dan check . 

### Missing value analysis

In [19]:
df.isnull().sum()

Unnamed: 0                0
Serial Number             0
List Year                 0
Date Recorded             2
Town                      0
Address                  51
Assessed Value            0
Sale Amount               0
Sales Ratio               0
Property Type        382446
Residential Type     398389
Non Use Code         784178
Assessor Remarks     926401
OPM remarks         1084598
Location             799518
dtype: int64

### Hapus kolom yang tidak diperlukan karena missing values nya banyak (Drop un-necassart coloums)

### Kalau kolom tidak ada, = jangan error.

In [35]:
df = df.drop(
    columns=[
        "Unnamed: 0",
        "OPM remarks",
        "Assessor Remarks"
    ],
    errors="ignore"
)

In [36]:
df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)

df.head()

### Check untuk ada duplikasi di baris nya , menghindari rata-rata harga real estate dan jumlah transaksi bisa mendukung chart nantinya

In [38]:
df.duplicated().sum()

np.int64(0)

### Filtering fungsi nya pemilihan data atas kondisi berdasarkan tujuan nya

In [39]:
df.columns

Index(['Serial Number', 'List Year', 'Date Recorded', 'Town', 'Address',
       'Assessed Value', 'Sale Amount', 'Sales Ratio', 'Property Type',
       'Residential Type', 'Non Use Code', 'Location'],
      dtype='str')

# Filter data tujuan nya   
##  Analisis trend , type, area  properti dengan periode tertentu. 
### Pada tahap ini, analisis dilakukan untuk melihat bagaimana perubahan median harga properti dan seterusnya
### Insight ini penting bagi investor untuk memahami apakah pasar properti sedang mengalami naik / turun.

In [41]:
yearly_median = df.groupby("List Year")["Sale Amount"].median().reset_index()

In [42]:
yearly_median.head()

   List Year  Sale Amount
0       2001     165000.0
1       2002     185000.0
2       2003     205000.0
3       2004     235000.0
4       2005     247000.0

### multi year filtering untuk mengetahui trend dari periode tertentu terlihat jelas seperti sekarang, sesudah vs sebelum covid
### type property serta lokasi dan range harga dari real eastate 
### mencari extreme data

In [43]:
df_recent = df[df["List Year"] >= 2020]

In [45]:
df_recent.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)

In [46]:
df_recent = df[df["List Year"] <= 2020]

In [49]:
df_recent.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
5,200500,2020,09/07/2021,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,NaN,NaN

### untuk residential

In [50]:
df_residential = df[df["Property Type"] == "Residential"]

In [51]:
df_residential.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)
5,200500,2020,09/07/2021,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,NaN,NaN

In [52]:
df_town = df[df["Town"] == "Greenwich"]

In [53]:
df_town.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
107,200630,2020,02/16/2021,Greenwich,2350000,1964480.0,2350000.0,0.8359,Residential,Single Family,NaN,NaN
108,200693,2020,03/05/2021,Greenwich,10 NIMITZ PLACE,548800.0,870000.0,0.6308,Residential,Single Family,NaN,NaN
109,200890,2020,04/22/2021,Greenwich,188 BIBLE STREET,737590.0,1364000.0,0.5407,Residential,Single Family,NaN,POINT (-73.59662 41.05717)
112,201711,2020,09/09/2021,Greenwich,15 SHOAL POINT ROAD,2623950.0,3900000.0,0.6728,Residential,Single Family,NaN,NaN
113,200386,2020,12/18/2020,Greenwich,328 LAKE AVENUE,1908690.0,2850000.0,0.6697,Residential,Single Family,NaN,NaN

### harga rumah yang akan melebihi dari 5% akan terhapus 
#### batas atas cap, dengan nilai jual nya yg extreme akan tidak diambil karena dikategorikan data extreme.

In [54]:
cap = df["Sale Amount"].quantile(0.95)

df_clean = df[df["Sale Amount"] <= cap]

In [55]:
df_clean.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)

In [57]:
df_valid = df[df["Sales Ratio"] > 0]

In [58]:
df_valid.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)

#### group berdasarkan tahun, bulan dengan kota dan type real estate

In [61]:
df.groupby("List Year")["Sale Amount"].median()

List Year
2001    165000.0
2002    185000.0
2003    205000.0
2004    235000.0
2005    247000.0
2006    265000.0
2007    245000.0
2008    215000.0
2009    217500.0
2010    210000.0
2011    213275.0
2012    220000.0
2013    206000.0
2014    214900.0
2015    210000.0
2016    225000.0
2017    225000.0
2018    225000.0
2019    253000.0
2020    285000.0
2021    310000.0
2022    322000.0
Name: Sale Amount, dtype: float64

### Table bulan dan tahun

In [66]:
df["Year"] = df["Date Recorded"].dt.year

In [69]:
df["Month"] = df["Date Recorded"].dt.month

In [75]:
df.groupby(["Year", "Month"])["Sale Amount"].median()

Year    Month
1999.0  4.0       95000.0
2001.0  8.0      596500.0
        9.0      256000.0
        10.0     150000.0
        11.0     155000.0
                   ...
2023.0  5.0      325000.0
        6.0      350000.0
        7.0      361500.0
        8.0      351000.0
        9.0      335000.0
Name: Sale Amount, Length: 267, dtype: float64

In [77]:
df["Date Recorded"] = pd.to_datetime(df["Date Recorded"])
df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location,Year,Month
0,2020177,2020,2021-04-14,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014),2021.0,4.0
1,2020225,2020,2021-05-26,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,2021.0,5.0
2,2020348,2020,2021-09-13,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN,2021.0,9.0
3,2020090,2020,2020-12-14,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,2020.0,12.0
4,210288,2021,2022-06-20,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988),2022.0,6.0

In [80]:
df.columns

Index(['Serial Number', 'List Year', 'Date Recorded', 'Town', 'Address',
       'Assessed Value', 'Sale Amount', 'Sales Ratio', 'Property Type',
       'Residential Type', 'Non Use Code', 'Location', 'Year', 'Month'],
      dtype='str')

In [81]:
df.groupby("List Year")["Sale Amount"].median()

List Year
2001    165000.0
2002    185000.0
2003    205000.0
2004    235000.0
2005    247000.0
2006    265000.0
2007    245000.0
2008    215000.0
2009    217500.0
2010    210000.0
2011    213275.0
2012    220000.0
2013    206000.0
2014    214900.0
2015    210000.0
2016    225000.0
2017    225000.0
2018    225000.0
2019    253000.0
2020    285000.0
2021    310000.0
2022    322000.0
Name: Sale Amount, dtype: float64

In [82]:
df.groupby(["Year", "Month"])["Sale Amount"].median()

Year    Month
1999.0  4.0       95000.0
2001.0  8.0      596500.0
        9.0      256000.0
        10.0     150000.0
        11.0     155000.0
                   ...
2023.0  5.0      325000.0
        6.0      350000.0
        7.0      361500.0
        8.0      351000.0
        9.0      335000.0
Name: Sale Amount, Length: 267, dtype: float64

In [83]:
df.groupby("Town")["Sale Amount"].median()

Town
***Unknown***    282450.0
Andover          218500.0
Ansonia          200000.0
Ashford          167000.0
Avon             358305.0
                   ...
Windsor Locks    176500.0
Wolcott          211000.0
Woodbridge       400000.0
Woodbury         270975.0
Woodstock        197500.0
Name: Sale Amount, Length: 170, dtype: float64

In [84]:
df.groupby("Property Type")["Sale Amount"].median()

Property Type
Apartments        500000.0
Commercial        400000.0
Condo             175000.0
Four Family       189450.0
Industrial        740000.0
Public Utility     44500.0
Residential       309900.0
Single Family     250000.0
Three Family      153000.0
Two Family        162000.0
Vacant Land       100000.0
Name: Sale Amount, dtype: float64

In [85]:
df.groupby("Residential Type")["Sale Amount"].median()

Residential Type
Condo            183500.0
Four Family      228700.0
Single Family    270000.0
Three Family     185000.0
Two Family       185000.0
Name: Sale Amount, dtype: float64

In [91]:
### Filter trend dari kategori real estate

In [92]:
df.groupby(["List Year", "Property Type"])["Sale Amount"].median()

List Year  Property Type
2006       Condo             197500.0
           Four Family       276750.0
           Single Family     303000.0
           Three Family      240000.0
           Two Family        235000.0
                               ...
2022       Commercial        380000.0
           Industrial        700000.0
           Public Utility    105000.0
           Residential       325000.0
           Vacant Land        95000.0
Name: Sale Amount, Length: 88, dtype: float64

In [93]:
### filter untuk melihar volume dari market

In [94]:
df.groupby("Town").size()

Town
***Unknown***       1
Andover           932
Ansonia          5017
Ashford          1467
Avon             7866
                 ...
Windsor Locks    4700
Wolcott          5241
Woodbridge       2788
Woodbury         3780
Woodstock        3345
Length: 170, dtype: int64

In [89]:
### Efesiensi dari penjualan per kota(town)

In [90]:
df.groupby("Town")["Sales Ratio"].mean()

Town
***Unknown***    0.235582
Andover          0.778054
Ansonia          0.908401
Ashford          0.902646
Avon             1.002314
                   ...
Windsor Locks    0.717097
Wolcott          0.842909
Woodbridge       1.013101
Woodbury         0.869538
Woodstock        1.184995
Name: Sales Ratio, Length: 170, dtype: float64

### filter untuk mengetahui pertumbuhan dari perubahan % dari baris sebelumnya berdasarkan tahun

In [103]:
yearly_table = pd.DataFrame({
    "Median Price": yearly,
    "Growth %": growth
})

print(yearly_table)

        Median Price   Growth %
Year
1999.0       95000.0        NaN
2001.0      154900.0  63.052632
2002.0      170000.0   9.748225
2003.0      189900.0  11.705882
2004.0      214250.0  12.822538
2005.0      240000.0  12.018670
2006.0      250000.0   4.166667
2007.0      265000.0   6.000000
2008.0      238000.0 -10.188679
2009.0      212000.0 -10.924370
2010.0      219000.0   3.301887
2011.0      206041.0  -5.917352
2012.0      215000.0   4.348164
2013.0      218000.0   1.395349
2014.0      207500.0  -4.816514
2015.0      211000.0   1.686747
2016.0      214500.0   1.658768
2017.0      225000.0   4.895105
2018.0      225000.0   0.000000
2019.0      229000.0   1.777778
2020.0      265000.0  15.720524
2021.0      291000.0   9.811321
2022.0      315000.0   8.247423
2023.0      326500.0   3.650794

### Ringkasan dari informasi di baris-baris sebelumnya di atas (row 103) ada data yang extreme sehingga dilakuakn recheck dengan df.describe nya

In [104]:
df.describe()

,Serial Number,List Year,Date Recorded,Assessed Value,Sale Amount,Sales Ratio,Year,Month
count,1.097629e+06,1.097629e+06,1097627,1.097629e+06,1.097629e+06,1.097629e+06,1.097627e+06,1.097627e+06
mean,5.370357e+05,2.011218e+03,2012-06-28 08:23:23.755556,2.818016e+05,4.053146e+05,9.603926e+00,2.011967e+03,6.817979e+00
min,0.000000e+00,2.001000e+03,1999-04-05 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,1.999000e+03,1.000000e+00
25%,3.071300e+04,2.005000e+03,2005-11-04 00:00:00,8.909000e+04,1.450000e+05,4.778667e-01,2.005000e+03,4.000000e+00
50%,8.070600e+04,2.011000e+03,2012-08-13 00:00:00,1.405800e+05,2.330000e+05,6.105663e-01,2.012000e+03,7.000000e+00
75%,1.703410e+05,2.018000e+03,2018-10-16 00:00:00,2.282700e+05,3.750000e+05,7.707200e-01,2.018000e+03,1.000000e+01
max,2.000500e+09,2.022000e+03,2023-09-29 00:00:00,8.815100e+08,5.000000e+09,1.226420e+06,2.023000e+03,1.200000e+01
std,7.526074e+06,6.773485e+00,NaN,1.657890e+06,5.143492e+06,1.801664e+03,6.779132e+00,3.247969e+00

In [105]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1097629 entries, 0 to 1097628
Data columns (total 14 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Serial Number     1097629 non-null  int64
 1   List Year         1097629 non-null  int64
 2   Date Recorded     1097627 non-null  datetime64[us]
 3   Town              1097629 non-null  str
 4   Address           1097578 non-null  str
 5   Assessed Value    1097629 non-null  float64
 6   Sale Amount       1097629 non-null  float64
 7   Sales Ratio       1097629 non-null  float64
 8   Property Type     715183 non-null   str
 9   Residential Type  699240 non-null   str
 10  Non Use Code      313451 non-null   object
 11  Location          298111 non-null   str
 12  Year              1097627 non-null  float64
 13  Month             1097627 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(2), object(1), str(5)
memory usage: 117.2+ MB

### Type property yang kosong di exclude

In [109]:
property_df = df_clean.dropna(subset=["Property Type"])

df = df.dropna(subset=["Property Type"])

In [112]:
property_df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)

In [113]:
df.info()

<class 'pandas.DataFrame'>
Index: 715183 entries, 0 to 1097628
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Serial Number     715183 non-null  int64
 1   List Year         715183 non-null  int64
 2   Date Recorded     715183 non-null  datetime64[us]
 3   Town              715183 non-null  str
 4   Address           715179 non-null  str
 5   Assessed Value    715183 non-null  float64
 6   Sale Amount       715183 non-null  float64
 7   Sales Ratio       715183 non-null  float64
 8   Property Type     715183 non-null  str
 9   Residential Type  699240 non-null  str
 10  Non Use Code      208968 non-null  object
 11  Location          226458 non-null  str
 12  Year              715183 non-null  float64
 13  Month             715183 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(2), object(1), str(5)
memory usage: 81.8+ MB

### Type residential yang kosong di exclude

In [116]:
property_df = df_clean.dropna(subset=["Residential Type"])

df = df.dropna(subset= ["Residential Type"])

In [117]:
property_df.head()

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Location
0,2020177,2020,04/14/2021,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014)
1,2020225,2020,05/26/2021,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
3,2020090,2020,12/14/2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,210288,2021,06/20/2022,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988)
5,200500,2020,09/07/2021,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,NaN,NaN

In [118]:
df.info()

<class 'pandas.DataFrame'>
Index: 699240 entries, 0 to 1097628
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Serial Number     699240 non-null  int64
 1   List Year         699240 non-null  int64
 2   Date Recorded     699240 non-null  datetime64[us]
 3   Town              699240 non-null  str
 4   Address           699236 non-null  str
 5   Assessed Value    699240 non-null  float64
 6   Sale Amount       699240 non-null  float64
 7   Sales Ratio       699240 non-null  float64
 8   Property Type     699240 non-null  str
 9   Residential Type  699240 non-null  str
 10  Non Use Code      201279 non-null  object
 11  Location          214091 non-null  str
 12  Year              699240 non-null  float64
 13  Month             699240 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(2), object(1), str(5)
memory usage: 80.0+ MB

### Memeriksa kolom ulang

In [119]:
df.isnull().sum()

Serial Number            0
List Year                0
Date Recorded            0
Town                     0
Address                  4
Assessed Value           0
Sale Amount              0
Sales Ratio              0
Property Type            0
Residential Type         0
Non Use Code        497961
Location            485149
Year                     0
Month                    0
dtype: int64

## Ringkasan Statistik

In [120]:
df.describe()

,Serial Number,List Year,Date Recorded,Assessed Value,Sale Amount,Sales Ratio,Year,Month
count,6.992400e+05,699240.000000,699240,6.992400e+05,6.992400e+05,6.992400e+05,699240.000000,699240.000000
mean,7.484256e+05,2014.717728,2015-12-28 07:45:11.584005,2.523573e+05,3.757951e+05,5.010083e+00,2015.461501,6.869095
min,2.100000e+01,2006.000000,1999-04-05 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,1999.000000,1.000000
25%,7.093175e+04,2011.000000,2011-10-05 00:00:00,1.106000e+05,1.570000e+05,5.536000e-01,2011.000000,4.000000
50%,1.404660e+05,2015.000000,2016-07-19 00:00:00,1.599000e+05,2.459000e+05,6.675000e-01,2016.000000,7.000000
75%,1.904870e+05,2019.000000,2020-05-29 00:00:00,2.481000e+05,3.860000e+05,8.136000e-01,2020.000000,10.000000
max,2.000500e+09,2022.000000,2023-09-29 00:00:00,8.815100e+08,3.187900e+08,1.226420e+06,2023.000000,12.000000
std,8.959386e+06,4.906458,NaN,1.280857e+06,9.232946e+05,1.680233e+03,4.922560,3.235183

### Dataframe baru setelah bersih

In [121]:
df_clean = df.copy()

In [122]:
df_clean.to_csv(
    "real_estate_clean.csv",
    index=False
)